#!/usr/bin/env bash

# OneRing Fleet: prompt for host metadata and emit a ready-to-run SSH helper script.
set -euo pipefail

script_dir="$(dirname "$0")"
cache_file="${script_dir}/.last_ssh_user"
umask 077

read -rp "Enter target host/IP: " host
[[ -n "$host" ]] || { echo "[ERROR] Host is required."; exit 1; }
[[ "$host" =~ ^[A-Za-z0-9._:-]+$ ]] || { echo "[ERROR] Host contains unsupported characters."; exit 1; }

while true; do
  read -rp "Enter VM ID (1-1000): " vm_id
  [[ "$vm_id" =~ ^[0-9]+$ ]] || { echo "[ERROR] VM ID must be digits only."; continue; }
  (( vm_id >= 1 && vm_id <= 1000 )) || { echo "[ERROR] VM ID must be between 1 and 1000."; continue; }
  break
done

default_user=""
[[ -f "$cache_file" ]] && default_user="$(<"$cache_file")"
if [[ -n "$default_user" ]]; then
  read -rp "Enter SSH username [${default_user}]: " user
  user="${user:-$default_user}"
else
  read -rp "Enter SSH username: " user
fi
[[ -n "$user" ]] || { echo "[ERROR] Username is required."; exit 1; }
[[ "$user" =~ ^[A-Za-z0-9._-]+$ ]] || { echo "[ERROR] Username contains unsupported characters."; exit 1; }
printf '%s\n' "$user" >"$cache_file"

read -rp "Enter script name (e.g., web_ssh.sh): " name_input
[[ -n "$name_input" ]] || { echo "[ERROR] Script name is required."; exit 1; }
[[ "$name_input" != */* ]] || { echo "[ERROR] Script name must not contain path separators."; exit 1; }

base_name="${name_input%.sh}"
[[ "$base_name" =~ ^[A-Za-z0-9._-]+$ ]] || { echo "[ERROR] Script name contains unsupported characters."; exit 1; }
[[ "$base_name" == *"_ssh" ]] || base_name="${base_name}_ssh"
script_name="${vm_id}_${base_name}.sh"

script_path="${script_dir}/${script_name}"
if [[ -e "$script_path" ]]; then
  read -rp "[WARN] ${script_name} already exists. Overwrite? (yes/no): " overwrite
  [[ "$overwrite" =~ ^[Yy][Ee][Ss]$ ]] || { echo "Aborted."; exit 1; }
fi

cat >"$script_path" <<EOF
#!/usr/bin/env bash
# Auto-generated by OneRing Fleet (generate_ssh_script.sh)
set -euo pipefail

HOST="${host}"
USER="${user}"
IDENTITY="\${IDENTITY:-\$HOME/.ssh/id_ed25519}"
SSH_OPTS=(
  -o BatchMode=yes
  -o StrictHostKeyChecking=yes
  -o ConnectTimeout=10
  -o ServerAliveInterval=10
  -o ServerAliveCountMax=3
)
[[ -f "\$IDENTITY" ]] && SSH_OPTS=(-i "\$IDENTITY" "\${SSH_OPTS[@]}")

ssh_run() { ssh "\${SSH_OPTS[@]}" "\${USER}@\${HOST}" "\$@"; }

if [[ \$# -eq 0 ]]; then
  read -r -p "SSH into \${USER}@\${HOST}? (yes/no): " answer
  [[ "\$answer" =~ ^[Yy][Ee][Ss]$ ]] || { echo "Aborted."; exit 0; }
  exec ssh "\${SSH_OPTS[@]}" "\${USER}@\${HOST}"
fi

if [[ "\$1" == "--update" ]]; then
  if ssh_run 'sudo -n /root/u.sh'; then
    echo "[OK] /root/u.sh completed on \${HOST}"
    exit 0
  else
    rc=\$?
    echo "[FAIL] /root/u.sh failed on \${HOST} (rc=\$rc)"
    exit \$rc
  fi
fi

if [[ "\$1" == "--help" || "\$1" == "-h" ]]; then
  cat <<'USAGE'
Usage: ./<host>_ssh.sh [--update | remote command]
  (no args)  Launch interactive SSH session after confirmation.
  --update   Run /root/u.sh with sudo -n.
  command    Execute any other command non-interactively.
Notes:
  - This helper assumes SSH key auth is already configured by the operator.
  - Restrict sudoers to the minimum commands needed in production.
USAGE
  exit 0
fi

if ssh_run "\$@"; then
  echo "[OK] Command completed on \${HOST}"
else
  rc=\$?
  echo "[FAIL] Command failed on \${HOST} (rc=\$rc)"
  exit \$rc
fi
EOF

chmod 700 "$script_path"
echo "[INFO] Generated ${script_path}"
